### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by o281700** [o281700/furima-32118#10]
### URL
https://furima-32118.herokuapp.com/

### Basic認証
ID: tm32118
Pass: 1q2w3e4r

### 出品者用
Email: sample@sample
Pass: 1qaz2wsx

### 購入者用
Email: test@com
Pass: 1qaz2wsx

### Test Card
Number: 4242424242424242
Exp: 3/33
CVC: 123

**Comment by mutorisa** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきていますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/65144927/100840801-c09c6080-34b9-11eb-97e2-8ae31394a7f6.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
